### PR TITLE
Remove schemas from HTTP requests

### PR DESCRIPTION
**Pull request by gotwalt**

### CODE REVIEW

**Comment by trentonstrong** [comment]
We need to change the validators on projector-api to remove the schema finally. Should create a chore for this.

**Comment by gotwalt** [comment]
Blocked by https://www.pivotaltracker.com/story/show/126094215

**Comment by omarkj** [comment]
Is there a reason we maintain the `data` key in the dictionary, instead of just having the request data flat at the root of the JSON document?

**Comment by gotwalt** [comment]
@omarkj I suppose it's there to prevent future key collisions in the event that we want to send metadata long with other requests. It's forwards-compatible, which is either good or bad, depending on how you look at it.

**Comment by omarkj** [comment]
This is unblocked.

**Pull request merged**
